// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import path from 'path'
import { defineConfig } from 'prisma/config'

export default defineConfig({
  earlyAccess: true,
  schema: path.join('prisma', 'schema.prisma'),
  migrate: {
    adapter: async () => {
      const { PrismaLibSQL } = await import('@prisma/adapter-libsql')
      // For SQLite file, use libsql file URL format
      return new PrismaLibSQL({
        url: `file:${path.join(process.cwd(), 'dev.db')}`,
      })
    },
  },
})